# Site
name: 'Sukriti'
description: 'Student'
logo: 
favicon: 
baseurl: 'Sukriti1312/Fork_Post'
disqus: 'demowebsite'
email: 
mailchimp-list:

include: ["_pages"]
permalink: /:title/
  
authors:
    sukriti:
      name:           Sukriti
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sukriti, a student"
      email:                  
      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
